name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Make Executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew buildRelease

      - name: Print the dirs
        run: ls app/build/outputs/apk/debug

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign
        with:
          releaseDirectory: app/build/outputs/apk/debug
          signingKeyBase64: ${{ secrets.KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.PASSWORD }}

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ${{ steps.sign.outputs.signedReleaseFile }}
